### ISSUE TITLE
Minecraft keeps crashing

### ISSUE THREAD

**Issue by HeroRyker** [FabricMC/community#113]
I don't know what mod is causing it.
https://pastebin.com/UKxsWgDt

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
