### ISSUE TITLE
??naming tag could mention the "conventional" names of each naming scheme

### ISSUE THREAD

**Issue by LeoCTH** [FabricMC/community#18]
something like
"Classes should be named with the first letter of each word capitalized, like this: `ThisIsAClass`. This is also known as *upper camel case*, or *Pascal case*."

**Comment by Scotsguy** [comment]
PascalCase, camelCase, (snake_case), SCREAMING_SNAKE_CASE

**Comment by LeoCTH** [comment]
SCREAMING_SNAKE_CASE :thonk:
regardless of the crazy and humorous name, it looks like its the most common name for it

**Comment by LeoCTH** [comment]
also PascalCase = UpperCamelCase
camelCase = (lower)CamelCase
