### ISSUE TITLE
Dev Life role approaches

### ISSUE THREAD

**Issue by gdude2002** [FabricMC/community#28]
Recently, the `Dev Life` role has been rendered useless on the Discord server, as it was barely used, users were obnoxiously removing it and re-adding it whenever there was any kind of drama, and Discord provides its own mechanisms for hiding channels. However, some users have pointed out that Discord doesn't provide a way to hide some channels while leaving other, muted channels visible — for example, you may want to hide the community channels but keep `#bot-posting` visible.

For this reason, I'd like to propose a couple new approaches.

* Return the functionality of the `Dev Life` role but, instead of providing a command for users to add/remove it at will, require users to request addition/removal via Modmail. We wouldn't be doing this with the intention of preventing users from switching (unless they switch unreasonably often), but it would add a little responsibility for users to commit to the role, should they choose to have it added.
* Return the functionality of the `Dev Life` role but, instead of providing an unlimited-use command, restrict its use to once per time period per user — for example, a user would only be able to add or remove it once in any 24-hour period.

Of course, we're also happy to discuss alternative approaches.

---

The following approaches have been discussed already, and we don't think they're viable.

* **Per-channel hiding system for users:** This would require either a role set up for each channel, or per-user permissions overrides for each channel. This isn't viable because Discord has fairly low limits on both of these things.

**Comment by redcreeper14385** [comment]
You can always disable `Hide Muted Channels` to access the bot channel, for example, and then enable it again. 

You can also just DM the bot, that works too, if it's just to make a quick Yarn query.

**Comment by TelepathicGrunt** [comment]
I’m not sure the modmail part is good but I definitely like the cooldown on the command. Perhaps maybe have it be 2 days? Or get extreme and a week minimum cooldown? I say this as 24 hour cooldown means people might still take it off when there’s drama and put it back on the next day. A longer cooldown will make them more likely to hesitate juggling the role. Make sure you have the bot reply that there’s a cooldown when the user puts it on.

**Comment by gdude2002** [comment]
That's a fair point. Ideally I would like it to be automated, on balance - the issue is, well, that's yet another thing on the pile of things I need to program

**Comment by LeoCTH** [comment]
Tbh the way *I* see the purpose of dev life is that if you are developing and you're truly busy, then you *shouldn't be paying attention to Discord at all*. I personally get distracted by it a **lot** so if you really want to focus and stop procrastinating, just log off Discord, do what you're supposed to do, then come back.

**Comment by LeoCTH** [comment]
If you dislike community channels, just mute them yourself, instead of clicking on a big red button to get a "get-out-of-drama-free-card".

**Comment by gdude2002** [comment]
There is an argument to be made here for working around discord's inadequate hiding tools, to be fair. I mean, that's half of why bots like that exist — try banning someone that isn't currently on your Discord server!

**Comment by TelepathicGrunt** [comment]
A lot of the api development and talk happens in the dev channels on discord so not checking discord isn’t an option. 

Furthermore, you may want to mute a channel so you don’t get notifications but still want to check it out later such as bot posting. No one wants to see “unread message” from bot posting lol. It’ll never be important. 

But if you have hide muted channels on, bot posting will always show up and you have no way of muting it without hiding it completely. That’s why we are discussing a role that does the hiding so you can keeps other channels muted without hiding those channels

**Comment by auoeke** [comment]
Discord recently introduced a solution that allows users to hide channels selectively and independently from muting them.
![Screenshot_20221225_084621](https://user-images.githubusercontent.com/44427720/209462042-ebfa84bb-a040-4a8d-9cad-b07759e0a29f.png)

**Comment by gdude2002** [comment]
I'm no longer part of Fabric, but the onboarding and channel selection feature is a considerably better solution and I recommend it over pretty much all other options.
