### ISSUE TITLE
Discord Meta: A Moderator Ethos

### ISSUE THREAD

**Issue by Arc-blroth** [FabricMC/community#29]
Recently, the discord has gone through quite a turbulent period, and many feel that it would better for there to be at least more transparency on moderator actions. On behalf of the community, I'd like to propose a Moderator Ethos, or a document that would outline the steps that moderators should take in all aspects of the discord, such as adding new features, removing old ones, and deciding infractions.

As a part of this ethos, I feel that it would be productive for new features to be discussed in issue posts such as this one. While #discord-meta and the admin channels serve as a place to pitch thoughts and share arguments, I believe that more finalized ideas should be submitted to this github to allow the entire community to preview and appeal changes. Issue threads should in no way replace #discord-meta - rather, they should supplement polished arguments from the meta channel.

In addition, I feel that we should establish a general timeline for the addition or removal of features from the discord, to allow the community to have time to discuss. An excellent example of such a timeline working is in fact the creation of this repository! (see #1) Though certain actions such as drama cleanup should have much a shorter timeframe than say adding a bot to the server, outlining a timeline for these scenarios should help give the community peace-of-mind.

**Comment by ToffeeMax** [comment]
**_Note: These are not official mod comment but personal thoughts_**

Overall I agree with the general premise of this post.  The document would need to be flexible enough to allow moderation discretion and allow users to understand why certain decisions were  - but if there is a standard is should be clear or a "Bright Line". If that is not possible then I am personally not a fan of such a document.

> As a part of this ethos, I feel that it would be productive for new features to be discussed in issue posts such as this one. While #discord-meta and the admin channels serve as a place to pitch thoughts and share arguments, I believe that more finalized ideas should be submitted to this github to allow the entire community to preview and appeal changes. Issue threads should in no way replace #discord-meta - rather, they should supplement polished arguments from the meta channel.

Totally agree here. 

> In addition, I feel that we should establish a general timeline for the addition or removal of features from the discord, to allow the community to have time to discuss. An excellent example of such a timeline working is in fact the creation of this repository! (see #1) Though certain actions such as drama cleanup should have much a shorter timeframe than say adding a bot to the server, outlining a timeline for these scenarios should help give the community peace-of-mind.

This is in the works! Recent discord-meta discussion and internal discussions are working towards this goal!
