### ISSUE TITLE
read what i said and allow discussion

### ISSUE THREAD

**Issue by moomooooo** [FabricMC/community#52]
didn't realized how bad this issue was. reading the post that was used to close my issue, it's clear you either didn't read the issue, or it all went in one ear, out through the other. I explained every argument that you made in my issue. On top of this, you locked the post why? We were all having a good dicussion... here is me repeating myself answering each of your points, again.

if fabric is all about being community driven, why r u locking a good discussion from continuing?
on top of that, locking it on an obviously open ended answer.

read it this time please.....

YOU-
This A) Reinforces the idea that we should prevent all discussion about them and keep to the discord TOS.
B) Explains why there may have been an influx of users joining asking about hacked clients.

MY ANSWER -
A) no it doesn't, I actually explained why it's not against discord TOS, I will paste from my original issue that you quite obviously did not read.
Kami-blue, 6200 members, has been around forever. Impact, a lot... I can't even tell tbh, 8k online, 3k donator roles rn. SalC1 has almost 600k subscribers and his entire channel is dedicated to this community, oh and he's a discord partner.
B) yes because there's a community that cares about this issue, and you are shutting them out for reasons that have already been proven redundant.

YOU -
The whole fabric toolchain is open soruce and under a license where people can use it to make these cheats. This is something I dont support and was clearly never supposed to be one of the intended uses of fabric.

MY ANSWER -
exactly my point, relating to utility mods... you argue that utility mods can be used to cheat, I argue that this is something I don't support and was clearly never supposed to be one of the intended uses of Utility Mods. I almost completely copied what u said there, because it proves my point, u say utility mods can be used to cheat, i give u and answer and tell u why fabric can also be used to cheat, u than answered the same exact way i did except replaced Utility Mod with the word Fabric... see my point here?

YOU -
Cheats have ruined a number of multiplayer games that I have played and its not something I wish upon anyone. The only people that are gaining anything out of it are the people who are extoring money of the people stupid enough to pay for them.

MY ANSWER - 
cheats have ruin honest games yes, the thing is these are an entirely different genre of "cheats" we are talking about here as implied in my original issue. It's even more supported that you don't actually know what you are talking about when you say "people who are extoring money of the people stupid enough to pay for them" because every Utility Mod I mentioned so far.... has been a free one. Every single big Utility Mod is free... Impact, kamiBLUE, wurstplustwo, gamesense, there are so many more, all are free.

YOU -
There is no way I am going to be on a discord server or part of a community that allows and promotes the use and creation of cheating/hacking software.

MY ANSWER - 
please, please, please read my original post.

please read, if you truly believe in a community driven modding api, please listen to a big portion of that community that has been shut out for about forever.

I understand your frustration with the hacking community, please understand mine, we are not the hacking community.

**Comment by OroArmor** [comment]
Learn that there are boundaries and anything that could be used for chea9is not allowed. Goodbye now

**Comment by moomooooo** [comment]
fabric can be used for cheating!

**Comment by ChiquitaV2** [comment]
I can confirm this to be true

**Comment by modmuss50** [comment]
dont open any more issues, otherwise I will need to start banning from github.

**Comment by OroArmor** [comment]
Yeah, but we won't help them.

Just like forge
