### ISSUE TITLE
A word on hack clients/utility mods

### ISSUE THREAD

**Issue by NirvanaNevermind** [FabricMC/community#56]
Hey, I'm not going to bother arguing that they should/not be allowed in fabricord, that's already been done and ignored.

Our main point that seems to have been lost in the process is that fabric must prepare itself for the large influx of cheaters that will come soon. This is not up to you, the majority of client devs do champion fabric over forge.

Now I don't know how you're going to tackle this, but ignoring each other's arguments in an argument doesn't work, sadly. There will be an influx, with tens of thousands of minecraft anarchy players moving to fabric from ye old forge 1.12.2.

They are coming, 2b2t's recent 1.16 tests have had very promising results thanks to A2H's achievement of what was long thought to be impossible: a fully scalable single world minecraft server. Oldf** is also preparing itself to update, among with many others tinkering silently.

These servers updating will cause a large increase in fabric cheat clients, just look at what an effect ECME has, many of the major 1.16 fabric cheats are designed for this server, with 50 - 100 players online. Now think of what effect a server with 1000 online will have.

Be prepared.

**Comment by i509VCB** [comment]
Noted.

**Comment by NirvanaNevermind** [comment]
Thank you, I do apologise on the way this has been handled, had the original point been said in the first place, I feel we would have had a much better outcome.

**Comment by modmuss50** [comment]
I fail to see how a single small server will cause a large influx of cheaters, there might be a few more but I dont see it becoming unmanageable.

I could always be wrong however.
